import Head from "next/head";
import React from "react";
import { Cover } from "../components/Cover";
import { FifthhtNews } from "../components/FifthNews";
import { FourthtNews } from "../components/FourthNews";
import { Header } from "../components/Header";
import { ImportantNews } from "../components/ImportantNews";
import { SecondNews } from "../components/SecondNews";
import { SeventhtNews } from "../components/Seventh";
import { SixthNews } from "../components/SixthNews";
import { ThirdtNews } from "../components/ThirdNews";
import { Times } from "../components/Times";

export default function Home() {
  return (
    <>
      <Head>
        <title>SeracNews - Novidades Internas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Cover />
      <SecondNews />
      <ThirdtNews />
      <FourthtNews />
      <FifthhtNews />
      {/* <ImportantNews />*/}
      <Times />
      <SixthNews />
      <SeventhtNews />
    </>
  );
}
